import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import {CssBaseline, ThemeProvider, Container} from "@mui/material";
import darkTheme from "@/app/dark.theme";

// Layout is a way to wrap your pages with a common layout. This is useful for things like headers, footers, and sidebars.

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AppRouterCacheProvider>
          <ThemeProvider theme={darkTheme}>
            <CssBaseline />
              <Container>
                {children}
              </Container>
          </ThemeProvider>
      </AppRouterCacheProvider>

      </body>
    </html>
  );
}
